name = "Bluewool"
author = "NotBjoggisAtAll"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac887dcef323ba003ea413c195d6b13ca8b2e2ec439b957bdf116526a70d3362"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.243"
