name = "Bluewool"
author = "NotBjoggisAtAll"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae88417e8bc9be83d915069caab10ca62675a3d77100de227baa1218818b6073"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.238"
