name = "Bluewool"
author = "NotBjoggisAtAll"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aea721f92a184407e9b8a1ef9f7eed03850635f613175440b507c7cc47110ef0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
